default: &default
  adapter: postgresql         
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: moving_map_app_development
  username: postgres
  password: password
  host: localhost

test:
  <<: *default
  database: moving_map_app_test
  username: postgres
  password: password
  host: localhost

production:
  <<: *default
  database: moving_map_app_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
